export const INITIAL_EMPLOYEES = [
  { name: "ALUISIO MACIEL SOARES", enrollment: "20138" },
  { name: "ANDERSON DOS SANTOS MOURA", enrollment: "17" },
  { name: "BRUNO VIEIRA DE OLIVEIRA", enrollment: " " },
  { name: "CARLOS ADRIANO FERREIRA DE ARAUJO", enrollment: "1" },
  { name: "CESAR AUGUSTO DE LIMA GOMES", enrollment: "700" },
  { name: "DENILSON RODRIGUES TORRES", enrollment: "871" },
  { name: "FRANCISCO DE ASSIS DE SOUSA PIMENTEL", enrollment: "1637" },
  { name: "GETULIO SOARES ARRUDA", enrollment: "205" },
  { name: "HUDSON CHAVES DA SILVA", enrollment: "1863" },
  { name: "IVANILDO BARBOSA DOS SANTOS", enrollment: "6" },
  { name: "JOFRE DOS SANTOS NASCIMENTO", enrollment: "1524" },
  { name: "JOHN LUCIO FENELON DA SILVA", enrollment: "1464" },
  { name: "JOSENEY MORENO DE SOUSA", enrollment: "1980" },
  { name: "LUCAS PAES DE SOUZA", enrollment: "1868" },
  { name: "LUIS HENRIQUE LOBATO DA SILVA", enrollment: "1398" },
  { name: "LUIZ EDUARDO DOS SANTOS MONTEIRO", enrollment: "20149" },
  { name: "MANUEL GARCIA NETO", enrollment: "1983" },
  { name: "MATHEUS BRITO BRAGA", enrollment: "1386" },
  { name: "MAURO DAISUKE MEDEIROS TAHARA", enrollment: "2142" },
  { name: "NATHAN HENRIQUE LEMOS DA SILVA", enrollment: "1467" },
  { name: "PAMELLA DE SOUZA ARAUJO", enrollment: "2451" },
  { name: "RAIMUNDO NONATO DA SILVA COSTA", enrollment: "1245" },
  { name: "ROBSON ALVES DA CRUZ", enrollment: "20145" },
  { name: "ROBSON DO AMARAL FRANCISCO DA SILVA", enrollment: "1526" },
  { name: "SOLISMA ALVES MARTINS", enrollment: "1246" },
  { name: "WESLLEY VINICIUS NEVES ALVES", enrollment: "1525" },
];
